### ISSUE TITLE
Matching column 'id' is not possible as this is an illegal attribute name in Mendix

### ISSUE THREAD

**Issue by Rvthof** [mendix/database-connector#3]
Some sort of mapping would be awesome.
Maybe adding an exception field for 'id' at least, as this is one of the most common column names in a database.
Could also do something like, if column is 'id', do entityname + '_id' to match it to an attribute?

**Comment by roland-mendix** [comment]
I've added a note to the Execute query How-To, explaining the issue with mapping the 'id' column, and how to work around it using an alias:
https://world.mendix.com/display/bestpractices/How+to+execute+an+SQL+select+query+on+an+external+database#HowtoexecuteanSQLselectqueryonanexternaldatabase-2.Preparation

**Comment by michaeldudli** [comment]
@Rvthof i run into the same issue, unfortunately the link doesnt work anymore. What's the solution for the id mapping when using the database connector?
